/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete.proyecto;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maric
 */
public class VentanaEstadoEnlace extends javax.swing.JFrame {
    
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form VentanaEstadoEnlace
     */
    public VentanaEstadoEnlace() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCantEnlace = new javax.swing.JTextField();
        txtCantRouter = new javax.swing.JTextField();
        txtRouterRaiz = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnIngreso_arista = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEscenario1 = new javax.swing.JButton();
        btnEscenario2 = new javax.swing.JButton();
        btnEscenario3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtejcucion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtUMemoria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel1.setText("ENRUTAMIENTO ESTADO-ENLACE");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Cantidad de routers en la topología:");

        jLabel3.setText("Router raíz:");

        jLabel4.setText("Cantidad de enlaces:");

        txtCantRouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantRouterActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnIngreso_arista.setText("Botón ingreso de aristas");
        btnIngreso_arista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngreso_aristaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtRouterRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCantRouter, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantEnlace, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnIngreso_arista)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevo)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtCantRouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantEnlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRouterRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo)
                    .addComponent(btnIngreso_arista))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Escenarios");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tabla de enrutamiento");

        btnEscenario1.setText("Escenario 1");
        btnEscenario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscenario1ActionPerformed(evt);
            }
        });

        btnEscenario2.setText("Escenario 2");
        btnEscenario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscenario2ActionPerformed(evt);
            }
        });

        btnEscenario3.setText("Escenario 3");
        btnEscenario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscenario3ActionPerformed(evt);
            }
        });

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane2.setViewportView(jTextArea);

        jLabel7.setText("TIEMPO DE EJECUCION:");

        txtejcucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtejcucionActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("10 routers");

        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("15 routers");

        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("20 routers");

        jLabel11.setForeground(new java.awt.Color(0, 102, 102));

        jLabel12.setText("UTILIZACION DE MEMORIA:");

        txtUMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUMemoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnEscenario2))
                            .addComponent(jLabel5))
                        .addGap(115, 115, 115))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addGap(47, 47, 47))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEscenario1)
                                        .addGap(145, 145, 145)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEscenario3)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtejcucion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtUMemoria))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel12))))
                                .addGap(0, 8, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(347, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(251, 251, 251)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEscenario3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnEscenario1)
                                .addComponent(btnEscenario2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtejcucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(210, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(146, 146, 146)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantRouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantRouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantRouterActionPerformed

    private void btnIngreso_aristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngreso_aristaActionPerformed
        // TODO add your handling code here:
        
        //Validacion de ingreso
        long inicio = System.currentTimeMillis();
        if (this.txtCantEnlace.getText().isEmpty() || this.txtCantRouter.getText().isEmpty()||
        this.txtRouterRaiz.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(this, "No ha ingresado correctamento los numeros.");
        }
        else
        {
            //Ingreso de la cantidad de router que hay en la topologia
            int cantRouter=Integer.parseInt(this.txtCantRouter.getText());
            int tablaEstadoEnlace[][]=new int[cantRouter][cantRouter]; //Se formara la tabla en base a la cantidad de router que se ingrese
            
            //Ingreso solo del router raiz
            int routRaiz=Integer.parseInt(this.txtRouterRaiz.getText());
            for (int i=0; i<cantRouter; i++)
            {   for (int j=0; j<cantRouter; j++)
                {
                    tablaEstadoEnlace[i][j]=1000;
                }
            }

            //Ingreso de la cantidad de enlaces
            int cantEnlace=Integer.parseInt(this.txtCantEnlace.getText());
            for(int i=0;i<cantEnlace;i++)
            {
                //Invocamos al metodo de IngresoDeArista
                //La cantidad de veces que se llame al método, será en base a la cantidad de enlaces que se 
                //observa en la tipologia
                IngresoDeArista(tablaEstadoEnlace);
            }
            
            
            int [][]tablaGeneral= TablaGeneralT(cantRouter,routRaiz);
            for(int i=0;i<cantRouter;i++){
                algoritmoDijkstra(cantRouter,tablaGeneral,tablaEstadoEnlace);
            }
            
            jTextArea.append("Router\tPeso \tRouter anterior\n");
            for (int i=0; i < tablaGeneral.length; i++) {
                this.jTextArea.append("\n\n");
                for (int j=0; j<3; j++) 
                {
                    this.jTextArea.append(tablaGeneral[i][j]+ "\t");
                }
            }
            
        long fin = System.currentTimeMillis();
        double tiempo = (double) ((fin - inicio)/1000);
        txtejcucion.setText(tiempo +" segundos");
        
        int dataSize= 1024 * 1024;
        Runtime runtime =Runtime.getRuntime();
        txtUMemoria.setText((runtime.totalMemory()-runtime.freeMemory())/dataSize + "MB");
                               
            //fuente: https://yoandroide.xyz/grafos-implementacion-algoritmo-dijkstra-en-java
            //fuente: https://professor-falken.com/programacion/java/como-conocer-la-cantidad-de-memoria-total-usada-y-libre-en-java/
        }
    }//GEN-LAST:event_btnIngreso_aristaActionPerformed

    private void btnEscenario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscenario1ActionPerformed
        // TODO add your handling code here:
        //Creamos un objeto con la clase Escenario1
        Escenario1 esc1 = new Escenario1();
        esc1.toFront();
        //Realiar que es esc1 se vizualice en la ventana principal
        esc1.setVisible(true);

    }//GEN-LAST:event_btnEscenario1ActionPerformed

    private void btnEscenario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscenario2ActionPerformed
        // TODO add your handling code here:
        //Creamos un objeto con la clase Escenario1
        Escenario2 esc2 = new Escenario2();
        esc2.toFront();
        //Realiar que es esc1 se vizualice en la ventana principal
        esc2.setVisible(true);
    }//GEN-LAST:event_btnEscenario2ActionPerformed

    private void btnEscenario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscenario3ActionPerformed
        // TODO add your handling code here:
                //Creamos un objeto con la clase Escenario1
        Escenario3 esc3 = new Escenario3();
        esc3.toFront();
        //Realiar que es esc1 se vizualice en la ventana principal
        esc3.setVisible(true);
    }//GEN-LAST:event_btnEscenario3ActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
         this.txtCantEnlace.setText("");
         this.txtCantRouter.setText("");
         this.txtRouterRaiz.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtejcucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtejcucionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtejcucionActionPerformed

    private void txtUMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUMemoriaActionPerformed

    //Metodos
    private static void IngresoDeArista(int[][]tablaEstadoEnlace ){
        //En base a los ingresos de del peso, numero del router inicial y final,
        //se almacenaran en la tablaArista
        int Inicio= Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el numero del router inicial:"));
        int Final= Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el numero del router final:"));
        int Peso= Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el peso:"));
        tablaEstadoEnlace[Inicio][Final]=Peso;
        
    }
    //Metodo auxiliar para algoritmoDijsktra
    private int routerConMenorRuta(int n,int[][]tabla){
        int posicionR=0;
        int menor =1000;
        for(int i=0; i<n; i++){
            if(tabla[i][3]!=1 && tabla[i][1]<= menor){
                menor = tabla[i][1];
                posicionR=i;   
            }
        }
        return posicionR;
    }
    //Por cada router se ejecutara el metodo algoritmoDijkstra()
    private void algoritmoDijkstra(int n,int[][]tabla,int[][]tablaEstadoEnlace){
        int posicion=routerConMenorRuta(n,tabla);
        tabla[posicion][3]=1;
        for(int i=0;i<n;i++){
            if(tablaEstadoEnlace[posicion][i]!=1000)
            {
                if(tablaEstadoEnlace[posicion][i]+tabla[posicion][1]<tabla[i][1])
                {
                    tabla[i][1]= tablaEstadoEnlace[posicion][i] + tabla[posicion][1];
                    tabla[i][2]=posicion;
                }  
            }
        }
    }
    
    private int[][] TablaGeneralT(int n,int rInic){
        
        int tabla[][]=new int[n][4];
        for(int i=0;i<n;i++){
            tabla[i][0]=i;
            tabla[i][1]=1000;
            tabla[i][2]=-1;        
            tabla[i][3]=0;
        }
        tabla[rInic][1]=0;
        return tabla;   
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadoEnlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadoEnlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadoEnlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadoEnlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEstadoEnlace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscenario1;
    private javax.swing.JButton btnEscenario2;
    private javax.swing.JButton btnEscenario3;
    private javax.swing.JButton btnIngreso_arista;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField txtCantEnlace;
    private javax.swing.JTextField txtCantRouter;
    private javax.swing.JTextField txtRouterRaiz;
    private javax.swing.JTextField txtUMemoria;
    private javax.swing.JTextField txtejcucion;
    // End of variables declaration//GEN-END:variables
}
